### ISSUE TITLE
The current version on Steam 13.2.3s still in English

### ISSUE THREAD

**Issue by XBoy1506** [serj1983/collegekings_russian_translate#2]
Except for the names everything else remains untranslated.

**Comment by serj1983** [comment]
Update the translation, see if you have fixed it?

**Comment by XBoy1506** [comment]
Всё [так же](https://i.ibb.co/jz3PbxW/20220506170456-1.jpg). Причём переведённые имена появляются ещё до прописи команды в консоли. Но в остальном всё по-прежнему на английском. Я уже и сейвы тёр в папке, и новую игру начинал.
P.S. Игра в стиме [бесплатная](https://store.steampowered.com/app/1463120/College_Kings__Act_I/), так что если хочешь, то можешь и сам проверить.

**Comment by serj1983** [comment]
У меня стим версия за основу взята, там же в руководствах есть обсуждение моего перевода.
По поводу ошибки, рекомендую полностью удалить игру из папки ~/.steam/steamapps/common/, закачать заново, залить мой перевод, из zip архива скопировать папку tl в папку College Kings\game\. Вашу ошибку я воспроизвести не смог, не под линуксом, не под виндами. Видимо вы некорректно разместили перевод или наложили на другой чей-то перевод.

**Comment by serj1983** [comment]
Да, в консоле печатаем печатаем renpy.change_language(‘russian’), а не renpy.change_language(‘Russian’). Забываю всё поправить.

**Comment by XBoy1506** [comment]
А, класс. Ну да, теперь всё работает.
